package ch.bailu.gtk.writer

import ch.bailu.gtk.model.*



public abstract class CodeWriter  implements Append {
    private final Writer out;

    private final GroupSpace group;


    public CodeWriter(Writer writer) {
        out = writer;
        group = new GroupSpace(out);
    }



    public abstract void writeStart(ClassModel classModel, NameSpaceModel namespaceModel) throws IOException;

    public abstract void writeClass(ClassModel classModel) throws IOException;

    public abstract void writeInterface(ClassModel classModel) throws IOException;

    public abstract void writeUnsupported(Model m) throws IOException;

    public abstract void writeInterfaceMethod(MethodModel m) throws IOException;

    public abstract void writeNativeMethod(ClassModel c, MethodModel m) throws IOException;

    public abstract void writeInternalConstructor(String className) throws IOException;

    public abstract void writeConstructor(ClassModel classModel, MethodModel m) throws IOException;

    public abstract void writeFactory(ClassModel classModel, MethodModel m) throws IOException;

    public abstract void writePrivateFactory(ClassModel classModel, MethodModel m) throws IOException;

    public abstract void writeConstant(ParameterModel p) throws IOException;

    public abstract void writeEnd() throws IOException;

    public abstract void writeSignal(ClassModel classModel, MethodModel signal) throws IOException;


    protected CodeWriter writeAutoGenerated() throws IOException {
        return a("/* this file is machine generated */\n\n");
    }


    @Override
    Append a(String toOut) throws IOException {
        out.append(toOut);
        return this;
    }

    protected CodeWriter start() throws IOException {
        group.start();
        return this;
    }

    protected CodeWriter start(int i) throws IOException {
        group.start(i);
        return this;
    }

    public CodeWriter next() {
        group.next();
        return this;
    }

    protected CodeWriter end(int i) {
        group.end(i);
        return this;
    }

}


