name: Build on Windows

on:
  pull_request:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2

      - name: Install GTK-4
        shell: msys2 {0}
        run: pacman -S mingw-w64-x86_64-gtk4

      - name: Version
        run: ./gradlew cV

      - name: Generate source code
        run: ./gradlew generate

      - name: Build library
        shell: msys2 {0}
        run: ./gradlew build
